[workspace]
members = ["xtask", "salsita", "salsita_bench"]
resolver = "3"

[workspace.package]
authors = ["Jasper van den Bogart"]
license = "MIT OR Apache-2.0"
edition = "2024"

[workspace.dependencies]
anyhow = { version = "1.0.98", default-features = false }
salsita = { path = "salsita", default-features = false }
serde = { version = "1.0.228", default-features = false, features = [
  "derive",
  "std",
] }
serde_json = { version = "1.0.145", default-features = false, features = [
  "alloc",
] }
xflags = { version = "0.3.2", default-features = false }
xshell = { version = "0.2.7", default-features = false }

[profile.release]
codegen-units = 1
debug = "line-tables-only"
incremental = true
lto = "fat"
strip = "debuginfo"

[workspace.lints.rust]
absolute-paths-not-starting-with-crate = "warn"
ambiguous-negative-literals = "warn"
closure-returning-async-block = "warn"
deprecated-in-future = "warn"
deprecated-safe = "warn"
deprecated-safe-2024 = "warn"
deref-into-dyn-supertrait = "warn"
edition-2024-expr-fragment-specifier = "allow"
elided-lifetimes-in-paths = "warn"
explicit-outlives-requirements = "warn"
ffi-unwind-calls = "warn"
if-let-rescope = "allow"
impl-trait-overcaptures = "warn"
impl-trait-redundant-captures = "warn"
keyword-idents-2024 = "allow"
let-underscore-drop = "warn"
linker-messages = "warn"
macro-use-extern-crate = "warn"
meta-variable-misuse = "warn"
missing-abi = "warn"
missing-copy-implementations = "warn"
missing-debug-implementations = "warn"
missing-docs = "allow"
missing-unsafe-on-extern = "warn"
non-ascii-idents = "warn"
non-local-definitions = "warn"
redundant-imports = "warn"
redundant-lifetimes = "warn"
rust-2024-guarded-string-incompatible-syntax = "allow"
rust-2024-incompatible-pat = "allow"
rust-2024-prelude-collisions = "allow"
single-use-lifetimes = "warn"
tail-expr-drop-order = "allow"
trivial-casts = "warn"
trivial-numeric-casts = "warn"
unit-bindings = "warn"
unnameable-types = "allow"
unreachable-pub = "warn"
unsafe-attr-outside-unsafe = "warn"
unsafe-code = "allow"
unsafe-op-in-unsafe-fn = "warn"
unstable-features = "warn"
unused-crate-dependencies = "warn"
unused-extern-crates = "warn"
unused-import-braces = "warn"
unused-lifetimes = "warn"
unused-macro-rules = "warn"
unused-qualifications = "allow"
unused-results = "allow"
variant-size-differences = "warn"

[workspace.lints.clippy]
absolute_paths = "allow"
absurd_extreme_comparisons = "warn"
alloc_instead_of_core = "warn"
allow_attributes = "warn"
allow_attributes_without_reason = "allow"
almost_complete_range = "warn"
almost_swapped = "warn"
approx_constant = "warn"
arbitrary_source_item_ordering = "allow"
arc_with_non_send_sync = "warn"
arithmetic_side_effects = "allow"
as_conversions = "allow"
as_pointer_underscore = "warn"
as_ptr_cast_mut = "warn"
as_underscore = "allow"
assertions_on_constants = "warn"
assertions_on_result_states = "warn"
assign_op_pattern = "warn"
assigning_clones = "warn"
async_yields_async = "warn"
await_holding_invalid_type = "warn"
await_holding_lock = "warn"
await_holding_refcell_ref = "warn"
bad_bit_mask = "warn"
big_endian_bytes = "warn"
bind_instead_of_map = "warn"
blanket_clippy_restriction_lints = "warn"
blocks_in_conditions = "warn"
bool_assert_comparison = "warn"
bool_comparison = "warn"
bool_to_int_with_if = "warn"
borrow_as_ptr = "warn"
borrow_deref_ref = "warn"
borrow_interior_mutable_const = "warn"
borrowed_box = "warn"
box_collection = "warn"
box_default = "warn"
boxed_local = "warn"
branches_sharing_code = "warn"
builtin_type_shadow = "warn"
byte_char_slices = "warn"
bytes_count_to_len = "warn"
bytes_nth = "warn"
cargo_common_metadata = "allow"
case_sensitive_file_extension_comparisons = "warn"
cast_abs_to_unsigned = "warn"
cast_enum_constructor = "warn"
cast_enum_truncation = "warn"
cast_lossless = "warn"
cast_nan_to_int = "warn"
cast_possible_truncation = "warn"
cast_possible_wrap = "warn"
cast_precision_loss = "warn"
cast_ptr_alignment = "warn"
cast_sign_loss = "warn"
cast_slice_different_sizes = "warn"
cast_slice_from_raw_parts = "warn"
cfg_not_test = "warn"
char_lit_as_u8 = "warn"
chars_last_cmp = "warn"
chars_next_cmp = "warn"
checked_conversions = "warn"
clear_with_drain = "warn"
clone_on_copy = "warn"
clone_on_ref_ptr = "warn"
cloned_instead_of_copied = "warn"
cmp_null = "warn"
cmp_owned = "warn"
cognitive_complexity = "warn"
collapsible_else_if = "warn"
collapsible_if = "warn"
collapsible_match = "warn"
collapsible_str_replace = "warn"
collection_is_never_read = "warn"
comparison_chain = "warn"
comparison_to_empty = "warn"
const_is_empty = "warn"
copy_iterator = "warn"
crate_in_macro_def = "warn"
create_dir = "warn"
crosspointer_transmute = "warn"
dbg_macro = "warn"
debug_assert_with_mut_call = "warn"
decimal_literal_representation = "warn"
declare_interior_mutable_const = "warn"
default_constructed_unit_structs = "warn"
default_instead_of_iter_empty = "warn"
default_numeric_fallback = "warn"
default_trait_access = "warn"
default_union_representation = "warn"
deprecated_cfg_attr = "warn"
deprecated_clippy_cfg_attr = "warn"
deprecated_semver = "warn"
deref_addrof = "warn"
deref_by_slicing = "warn"
derivable_impls = "warn"
derive_ord_xor_partial_ord = "warn"
derive_partial_eq_without_eq = "warn"
derived_hash_with_manual_eq = "warn"
disallowed_macros = "warn"
disallowed_methods = "warn"
disallowed_names = "warn"
disallowed_script_idents = "allow"
disallowed_types = "warn"
diverging_sub_expression = "warn"
doc_comment_double_space_linebreaks = "warn"
doc_include_without_cfg = "warn"
doc_lazy_continuation = "warn"
doc_link_code = "warn"
doc_link_with_quotes = "warn"
doc_markdown = "warn"
doc_nested_refdefs = "warn"
doc_overindented_list_items = "warn"
double_comparisons = "warn"
double_ended_iterator_last = "warn"
double_must_use = "warn"
double_parens = "warn"
drain_collect = "warn"
drop_non_drop = "warn"
duplicate_mod = "warn"
duplicate_underscore_argument = "warn"
duplicated_attributes = "warn"
duration_subsec = "warn"
eager_transmute = "warn"
elidable_lifetime_names = "warn"
else_if_without_else = "warn"
empty_docs = "warn"
empty_drop = "warn"
empty_enum = "warn"
empty_enum_variants_with_brackets = "warn"
empty_line_after_doc_comments = "warn"
empty_line_after_outer_attr = "warn"
empty_loop = "warn"
empty_structs_with_brackets = "warn"
enum_clike_unportable_variant = "warn"
enum_glob_use = "warn"
enum_variant_names = "warn"
eq_op = "warn"
equatable_if_let = "warn"
erasing_op = "warn"
err_expect = "warn"
error_impl_error = "warn"
excessive_nesting = "warn"
excessive_precision = "warn"
exhaustive_enums = "allow"
exhaustive_structs = "allow"
exit = "warn"
expect_fun_call = "warn"
expect_used = "allow"
expl_impl_clone_on_copy = "warn"
explicit_auto_deref = "warn"
explicit_counter_loop = "warn"
explicit_deref_methods = "warn"
explicit_into_iter_loop = "warn"
explicit_iter_loop = "warn"
explicit_write = "warn"
extend_with_drain = "warn"
extra_unused_lifetimes = "warn"
extra_unused_type_parameters = "warn"
fallible_impl_from = "warn"
field_reassign_with_default = "warn"
field_scoped_visibility_modifiers = "allow"
filetype_is_file = "warn"
filter_map_bool_then = "warn"
filter_map_identity = "warn"
filter_map_next = "warn"
filter_next = "warn"
flat_map_identity = "warn"
flat_map_option = "warn"
float_arithmetic = "allow"
float_cmp = "warn"
float_cmp_const = "warn"
float_equality_without_abs = "warn"
fn_params_excessive_bools = "warn"
fn_to_numeric_cast = "warn"
fn_to_numeric_cast_any = "warn"
fn_to_numeric_cast_with_truncation = "warn"
for_kv_map = "warn"
forget_non_drop = "warn"
format_collect = "warn"
format_in_format_args = "warn"
format_push_string = "warn"
four_forward_slashes = "warn"
from_iter_instead_of_collect = "warn"
from_over_into = "warn"
from_raw_with_void_ptr = "warn"
from_str_radix_10 = "warn"
future_not_send = "warn"
get_first = "warn"
get_last_with_len = "warn"
get_unwrap = "warn"
host_endian_bytes = "allow"
identity_op = "warn"
if_let_mutex = "warn"
if_not_else = "warn"
if_same_then_else = "warn"
if_then_some_else_none = "warn"
ifs_same_cond = "warn"
ignored_unit_patterns = "warn"
impl_hash_borrow_with_str_and_bytes = "warn"
impl_trait_in_params = "warn"
implicit_clone = "warn"
implicit_hasher = "warn"
implicit_return = "allow"
implicit_saturating_add = "warn"
implicit_saturating_sub = "warn"
implied_bounds_in_impls = "warn"
impossible_comparisons = "warn"
imprecise_flops = "warn"
incompatible_msrv = "warn"
inconsistent_digit_grouping = "warn"
inconsistent_struct_constructor = "allow"
index_refutable_slice = "warn"
indexing_slicing = "warn"
ineffective_bit_mask = "warn"
ineffective_open_options = "warn"
inefficient_to_string = "warn"
infallible_destructuring_match = "warn"
infinite_iter = "warn"
infinite_loop = "warn"
inherent_to_string = "warn"
inherent_to_string_shadow_display = "warn"
init_numbered_fields = "warn"
inline_always = "warn"
inline_asm_x86_att_syntax = "allow"
inline_asm_x86_intel_syntax = "allow"
inline_fn_without_body = "warn"
inspect_for_each = "warn"
int_plus_one = "warn"
integer_division = "allow"
integer_division_remainder_used = "allow"
into_iter_on_ref = "warn"
into_iter_without_iter = "warn"
invalid_regex = "warn"
invalid_upcast_comparisons = "warn"
inverted_saturating_sub = "warn"
invisible_characters = "warn"
io_other_error = "warn"
is_digit_ascii_radix = "warn"
items_after_statements = "allow"
items_after_test_module = "warn"
iter_cloned_collect = "warn"
iter_count = "warn"
iter_filter_is_ok = "warn"
iter_filter_is_some = "warn"
iter_kv_map = "warn"
iter_next_loop = "warn"
iter_next_slice = "warn"
iter_not_returning_iterator = "warn"
iter_nth = "warn"
iter_nth_zero = "warn"
iter_on_empty_collections = "warn"
iter_on_single_items = "warn"
iter_out_of_bounds = "warn"
iter_over_hash_type = "allow"
iter_overeager_cloned = "warn"
iter_skip_next = "warn"
iter_skip_zero = "warn"
iter_with_drain = "allow"
iter_without_into_iter = "warn"
iterator_step_by_zero = "warn"
join_absolute_paths = "warn"
just_underscores_and_digits = "warn"
large_const_arrays = "warn"
large_digit_groups = "warn"
large_enum_variant = "warn"
large_futures = "warn"
large_include_file = "allow"
large_stack_arrays = "warn"
large_stack_frames = "warn"
large_types_passed_by_value = "warn"
legacy_numeric_constants = "warn"
len_without_is_empty = "warn"
len_zero = "warn"
let_and_return = "warn"
let_underscore_future = "warn"
let_underscore_lock = "warn"
let_underscore_must_use = "warn"
let_underscore_untyped = "allow"
let_unit_value = "warn"
let_with_type_underscore = "warn"
lines_filter_map_ok = "warn"
linkedlist = "allow"
lint_groups_priority = "warn"
literal_string_with_formatting_args = "warn"
little_endian_bytes = "allow"
lossy_float_literal = "warn"
macro_metavars_in_unsafe = "warn"
macro_use_imports = "warn"
main_recursion = "warn"
manual_assert = "warn"
manual_async_fn = "warn"
manual_bits = "warn"
manual_c_str_literals = "warn"
manual_clamp = "warn"
manual_contains = "warn"
manual_div_ceil = "warn"
manual_filter = "warn"
manual_filter_map = "warn"
manual_find = "warn"
manual_find_map = "warn"
manual_flatten = "warn"
manual_hash_one = "warn"
manual_ignore_case_cmp = "warn"
manual_inspect = "warn"
manual_instant_elapsed = "warn"
manual_is_ascii_check = "warn"
manual_is_finite = "warn"
manual_is_infinite = "warn"
manual_is_power_of_two = "warn"
manual_is_variant_and = "warn"
manual_let_else = "warn"
manual_main_separator_str = "warn"
manual_map = "warn"
manual_memcpy = "warn"
manual_midpoint = "warn"
manual_next_back = "warn"
manual_non_exhaustive = "warn"
manual_ok_err = "warn"
manual_ok_or = "warn"
manual_option_as_slice = "warn"
manual_pattern_char_comparison = "warn"
manual_range_contains = "warn"
manual_range_patterns = "warn"
manual_rem_euclid = "warn"
manual_repeat_n = "warn"
manual_retain = "warn"
manual_rotate = "warn"
manual_saturating_arithmetic = "warn"
manual_slice_fill = "warn"
manual_slice_size_calculation = "warn"
manual_split_once = "warn"
manual_str_repeat = "warn"
manual_string_new = "warn"
manual_strip = "warn"
manual_swap = "warn"
manual_try_fold = "warn"
manual_unwrap_or = "warn"
manual_unwrap_or_default = "warn"
manual_while_let_some = "warn"
many_single_char_names = "warn"
map_all_any_identity = "warn"
map_clone = "warn"
map_collect_result_unit = "warn"
map_entry = "warn"
map_err_ignore = "warn"
map_flatten = "warn"
map_identity = "warn"
map_unwrap_or = "warn"
map_with_unused_argument_over_ranges = "warn"
match_as_ref = "warn"
match_bool = "warn"
match_like_matches_macro = "warn"
match_overlapping_arm = "warn"
match_ref_pats = "warn"
match_result_ok = "warn"
match_same_arms = "warn"
match_single_binding = "warn"
match_str_case_mismatch = "warn"
match_wild_err_arm = "warn"
match_wildcard_for_single_variants = "warn"
maybe_infinite_iter = "warn"
mem_forget = "warn"
mem_replace_option_with_none = "warn"
mem_replace_option_with_some = "warn"
mem_replace_with_default = "warn"
mem_replace_with_uninit = "warn"
min_ident_chars = "allow"
min_max = "warn"
mismatching_type_param_order = "warn"
misnamed_getters = "warn"
misrefactored_assign_op = "warn"
missing_assert_message = "allow"
missing_asserts_for_indexing = "warn"
missing_const_for_fn = "warn"
missing_const_for_thread_local = "warn"
missing_docs_in_private_items = "allow"
missing_enforced_import_renames = "warn"
missing_errors_doc = "allow"
missing_fields_in_debug = "warn"
missing_inline_in_public_items = "allow"
missing_panics_doc = "allow"
missing_safety_doc = "warn"
missing_spin_loop = "warn"
missing_trait_methods = "allow"
missing_transmute_annotations = "warn"
mistyped_literal_suffixes = "warn"
mixed_attributes_style = "warn"
mixed_case_hex_literals = "warn"
mixed_read_write_in_expression = "warn"
mod_module_files = "warn"
module_inception = "warn"
module_name_repetitions = "allow"
modulo_arithmetic = "allow"
modulo_one = "warn"
multi_assignments = "warn"
multiple_bound_locations = "warn"
multiple_crate_versions = "allow"
multiple_inherent_impl = "warn"
multiple_unsafe_ops_per_block = "warn"
must_use_candidate = "warn"
must_use_unit = "warn"
mut_from_ref = "warn"
mut_mut = "warn"
mut_mutex_lock = "warn"
mut_range_bound = "warn"
mutable_key_type = "warn"
mutex_atomic = "warn"
mutex_integer = "warn"
naive_bytecount = "warn"
needless_arbitrary_self_type = "warn"
needless_as_bytes = "warn"
needless_bitwise_bool = "warn"
needless_bool = "warn"
needless_bool_assign = "warn"
needless_borrow = "warn"
needless_borrowed_reference = "warn"
needless_borrows_for_generic_args = "warn"
needless_character_iteration = "warn"
needless_collect = "warn"
needless_continue = "warn"
needless_doctest_main = "warn"
needless_else = "warn"
needless_for_each = "warn"
needless_if = "warn"
needless_late_init = "warn"
needless_lifetimes = "warn"
needless_match = "warn"
needless_maybe_sized = "warn"
needless_option_as_deref = "warn"
needless_option_take = "warn"
needless_parens_on_range_literals = "warn"
needless_pass_by_ref_mut = "warn"
needless_pass_by_value = "warn"
needless_pub_self = "warn"
needless_question_mark = "warn"
needless_range_loop = "warn"
needless_raw_string_hashes = "warn"
needless_raw_strings = "warn"
needless_return = "warn"
needless_return_with_question_mark = "warn"
needless_splitn = "warn"
needless_update = "warn"
neg_cmp_op_on_partial_ord = "warn"
neg_multiply = "warn"
negative_feature_names = "warn"
never_loop = "warn"
new_ret_no_self = "warn"
new_without_default = "warn"
no_effect = "warn"
no_effect_replace = "warn"
no_effect_underscore_binding = "warn"
no_mangle_with_rust_abi = "warn"
non_ascii_literal = "allow"
non_canonical_clone_impl = "warn"
non_canonical_partial_ord_impl = "warn"
non_minimal_cfg = "warn"
non_octal_unix_permissions = "warn"
non_send_fields_in_send_ty = "warn"
non_std_lazy_statics = "warn"
non_zero_suggestions = "warn"
nonminimal_bool = "warn"
nonsensical_open_options = "warn"
nonstandard_macro_braces = "warn"
not_unsafe_ptr_arg_deref = "warn"
obfuscated_if_else = "warn"
octal_escapes = "warn"
ok_expect = "warn"
only_used_in_recursion = "warn"
op_ref = "warn"
option_as_ref_cloned = "warn"
option_as_ref_deref = "warn"
option_env_unwrap = "warn"
option_filter_map = "warn"
option_if_let_else = "warn"
option_map_or_none = "warn"
option_map_unit_fn = "warn"
option_option = "warn"
or_fun_call = "allow"
or_then_unwrap = "warn"
out_of_bounds_indexing = "warn"
overly_complex_bool_expr = "warn"
owned_cow = "warn"
panic = "allow"
panic_in_result_fn = "warn"
panicking_overflow_checks = "warn"
panicking_unwrap = "warn"
partial_pub_fields = "warn"
partialeq_ne_impl = "warn"
partialeq_to_none = "warn"
path_buf_push_overwrite = "warn"
path_ends_with_ext = "warn"
pathbuf_init_then_push = "allow"
pattern_type_mismatch = "allow"
permissions_set_readonly_false = "warn"
pointers_in_nomem_asm_block = "warn"
possible_missing_comma = "warn"
precedence = "warn"
precedence_bits = "warn"
print_in_format_impl = "warn"
print_literal = "warn"
print_stderr = "allow"
print_stdout = "allow"
print_with_newline = "warn"
println_empty_string = "warn"
ptr_arg = "warn"
ptr_as_ptr = "warn"
ptr_cast_constness = "warn"
ptr_eq = "warn"
ptr_offset_with_cast = "warn"
pub_underscore_fields = "warn"
pub_use = "allow"
pub_with_shorthand = "allow"
pub_without_shorthand = "warn"
question_mark = "warn"
question_mark_used = "allow"
range_minus_one = "warn"
range_plus_one = "warn"
range_zip_with_len = "warn"
rc_buffer = "warn"
rc_clone_in_vec_init = "warn"
rc_mutex = "warn"
read_line_without_trim = "warn"
read_zero_byte_vec = "warn"
readonly_write_lock = "warn"
recursive_format_impl = "warn"
redundant_allocation = "warn"
redundant_as_str = "warn"
redundant_async_block = "warn"
redundant_at_rest_pattern = "warn"
redundant_clone = "warn"
redundant_closure = "warn"
redundant_closure_call = "warn"
redundant_closure_for_method_calls = "warn"
redundant_comparisons = "warn"
redundant_else = "warn"
redundant_feature_names = "warn"
redundant_field_names = "warn"
redundant_guards = "warn"
redundant_locals = "warn"
redundant_pattern = "warn"
redundant_pattern_matching = "warn"
redundant_pub_crate = "allow"
redundant_slicing = "warn"
redundant_static_lifetimes = "warn"
redundant_test_prefix = "warn"
redundant_type_annotations = "warn"
ref_as_ptr = "warn"
ref_binding_to_reference = "warn"
ref_option = "warn"
ref_option_ref = "warn"
ref_patterns = "allow"
regex_creation_in_loops = "warn"
renamed_function_params = "warn"
repeat_once = "warn"
repeat_vec_with_capacity = "warn"
repr_packed_without_abi = "warn"
reserve_after_initialization = "warn"
rest_pat_in_fully_bound_structs = "warn"
result_filter_map = "warn"
result_large_err = "warn"
result_map_or_into_option = "warn"
result_map_unit_fn = "warn"
result_unit_err = "warn"
return_and_then = "warn"
return_self_not_must_use = "warn"
reversed_empty_ranges = "warn"
same_functions_in_if_condition = "warn"
same_item_push = "warn"
same_name_method = "warn"
search_is_some = "warn"
seek_from_current = "warn"
seek_to_start_instead_of_rewind = "warn"
self_assignment = "warn"
self_named_constructors = "warn"
self_named_module_files = "allow"
semicolon_if_nothing_returned = "allow"
semicolon_inside_block = "allow"
semicolon_outside_block = "warn"
separated_literal_suffix = "warn"
serde_api_misuse = "warn"
set_contains_or_insert = "warn"
shadow_reuse = "allow"
shadow_same = "allow"
shadow_unrelated = "allow"
short_circuit_statement = "warn"
should_implement_trait = "warn"
should_panic_without_expect = "warn"
significant_drop_in_scrutinee = "warn"
significant_drop_tightening = "allow"
similar_names = "allow"
single_call_fn = "allow"
single_char_add_str = "warn"
single_char_lifetime_names = "allow"
single_char_pattern = "warn"
single_component_path_imports = "warn"
single_element_loop = "warn"
single_match = "warn"
single_match_else = "warn"
single_option_map = "warn"
single_range_in_vec_init = "warn"
size_of_in_element_count = "warn"
size_of_ref = "warn"
skip_while_next = "warn"
sliced_string_as_bytes = "warn"
slow_vector_initialization = "warn"
stable_sort_primitive = "warn"
std_instead_of_alloc = "warn"
std_instead_of_core = "warn"
str_split_at_newline = "warn"
str_to_string = "warn"
string_add = "warn"
string_add_assign = "warn"
string_extend_chars = "warn"
string_from_utf8_as_bytes = "warn"
string_lit_as_bytes = "warn"
string_lit_chars_any = "warn"
string_slice = "allow"
strlen_on_c_strings = "warn"
struct_excessive_bools = "warn"
struct_field_names = "warn"
suboptimal_flops = "warn"
suspicious_arithmetic_impl = "warn"
suspicious_assignment_formatting = "warn"
suspicious_command_arg_space = "warn"
suspicious_doc_comments = "warn"
suspicious_else_formatting = "warn"
suspicious_map = "warn"
suspicious_op_assign_impl = "warn"
suspicious_open_options = "warn"
suspicious_operation_groupings = "warn"
suspicious_splitn = "warn"
suspicious_to_owned = "warn"
suspicious_unary_op_formatting = "warn"
suspicious_xor_used_as_pow = "warn"
swap_ptr_to_ref = "warn"
tabs_in_doc_comments = "warn"
temporary_assignment = "warn"
test_attr_in_doctest = "warn"
tests_outside_test_module = "warn"
to_digit_is_some = "warn"
to_string_in_format_args = "warn"
to_string_trait_impl = "warn"
todo = "warn"
too_long_first_doc_paragraph = "warn"
too_many_arguments = "warn"
too_many_lines = "allow"
toplevel_ref_arg = "warn"
trailing_empty_array = "warn"
trait_duplication_in_bounds = "warn"
transmute_bytes_to_str = "warn"
transmute_int_to_bool = "warn"
transmute_int_to_non_zero = "warn"
transmute_null_to_fn = "warn"
transmute_ptr_to_ptr = "warn"
transmute_ptr_to_ref = "warn"
transmute_undefined_repr = "warn"
transmutes_expressible_as_ptr_casts = "warn"
transmuting_null = "warn"
trim_split_whitespace = "warn"
trivial_regex = "warn"
trivially_copy_pass_by_ref = "warn"
try_err = "warn"
tuple_array_conversions = "warn"
type_complexity = "warn"
type_id_on_box = "warn"
type_repetition_in_bounds = "warn"
unbuffered_bytes = "warn"
unchecked_duration_subtraction = "warn"
unconditional_recursion = "warn"
undocumented_unsafe_blocks = "warn"
unicode_not_nfc = "warn"
unimplemented = "warn"
uninhabited_references = "warn"
uninit_assumed_init = "warn"
uninit_vec = "warn"
uninlined_format_args = "warn"
unit_arg = "warn"
unit_cmp = "warn"
unit_hash = "warn"
unit_return_expecting_ord = "warn"
unnecessary_box_returns = "warn"
unnecessary_cast = "warn"
unnecessary_clippy_cfg = "warn"
unnecessary_debug_formatting = "warn"
unnecessary_fallible_conversions = "warn"
unnecessary_filter_map = "warn"
unnecessary_find_map = "warn"
unnecessary_first_then_check = "warn"
unnecessary_fold = "warn"
unnecessary_get_then_check = "warn"
unnecessary_join = "warn"
unnecessary_lazy_evaluations = "warn"
unnecessary_literal_bound = "warn"
unnecessary_literal_unwrap = "warn"
unnecessary_map_on_constructor = "warn"
unnecessary_map_or = "warn"
unnecessary_min_or_max = "warn"
unnecessary_mut_passed = "warn"
unnecessary_operation = "warn"
unnecessary_owned_empty_strings = "warn"
unnecessary_result_map_or_else = "warn"
unnecessary_safety_comment = "warn"
unnecessary_safety_doc = "warn"
unnecessary_self_imports = "warn"
unnecessary_semicolon = "warn"
unnecessary_sort_by = "warn"
unnecessary_struct_initialization = "warn"
unnecessary_to_owned = "warn"
unnecessary_unwrap = "warn"
unnecessary_wraps = "warn"
unneeded_field_pattern = "allow"
unneeded_struct_pattern = "warn"
unneeded_wildcard_pattern = "warn"
unnested_or_patterns = "warn"
unreachable = "allow"
unreadable_literal = "warn"
unsafe_derive_deserialize = "warn"
unsafe_removed_from_name = "warn"
unseparated_literal_suffix = "allow"
unsound_collection_transmute = "warn"
unused_async = "warn"
unused_enumerate_index = "warn"
unused_format_specs = "warn"
unused_io_amount = "warn"
unused_peekable = "warn"
unused_result_ok = "warn"
unused_rounding = "warn"
unused_self = "warn"
unused_trait_names = "warn"
unused_unit = "warn"
unusual_byte_groupings = "warn"
unwrap_in_result = "allow"
unwrap_or_default = "warn"
unwrap_used = "warn"
upper_case_acronyms = "warn"
use_debug = "allow"
use_self = "warn"
used_underscore_binding = "allow"
used_underscore_items = "warn"
useless_asref = "warn"
useless_attribute = "warn"
useless_conversion = "warn"
useless_format = "warn"
useless_let_if_seq = "warn"
useless_nonzero_new_unchecked = "warn"
useless_transmute = "warn"
useless_vec = "warn"
vec_box = "warn"
vec_init_then_push = "warn"
vec_resize_to_zero = "warn"
verbose_bit_mask = "warn"
verbose_file_reads = "warn"
waker_clone_wake = "warn"
while_float = "warn"
while_immutable_condition = "warn"
while_let_loop = "warn"
while_let_on_iterator = "warn"
wildcard_dependencies = "warn"
wildcard_enum_match_arm = "allow"
wildcard_imports = "warn"
wildcard_in_or_patterns = "warn"
write_literal = "warn"
write_with_newline = "warn"
writeln_empty_string = "warn"
wrong_self_convention = "warn"
wrong_transmute = "warn"
zero_divided_by_zero = "warn"
zero_prefixed_literal = "warn"
zero_ptr = "warn"
zero_repeat_side_effects = "warn"
zero_sized_map_values = "warn"
zombie_processes = "warn"
zst_offset = "warn"

[workspace.lints.rustdoc]
missing_crate_level_docs = "warn"
private_doc_tests = "warn"
unescaped_backticks = "warn"
